In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('user1_data.csv')
df2 = pd.read_csv('user2_data.csv')

In [3]:
df1.head(15)

                  ttime   pm1  pm2  pm3   am      sm     st      lum
0   2022-07-18 15:42:55  3.63  0.0  0.0  3.2  7813.0  25.65  15001.0
1   2022-07-18 15:47:55  4.19  0.0  0.0  4.8  7692.0  25.66  13863.0
2   2022-07-18 15:52:55  4.74  0.0  0.0  4.0  7813.0  25.67  13788.0
3   2022-07-18 15:57:55  5.30  0.0  0.0  4.8  7813.0  25.68  14383.0
4   2022-07-18 16:02:55  0.55  5.3  5.3  3.2  7813.0  25.69  14621.0
5   2022-07-18 16:07:55  1.11  5.3  5.3  4.0  7813.0  25.71  13782.0
6   2022-07-18 16:13:03  1.67  5.3  5.3  1.6  7813.0  25.72  12681.0
7   2022-07-18 16:17:55  2.23  5.3  5.3  6.4  7813.0  25.73  12226.0
8   2022-07-18 16:22:55  2.79  5.3  5.3  1.6  7813.0  25.74  10509.0
9   2022-07-18 16:27:55  3.35  5.3  5.3  3.2  7692.0  25.75  10041.0
10  2022-07-18 16:32:55  3.91  5.3  5.3  5.6  7692.0  25.76   8021.0
11  2022-07-18 16:37:55  4.47  5.3  5.3  4.0  7813.0  25.78  10340.0
12  2022-07-18 16:42:55  5.02  5.3  5.3  5.6  7692.0  25.79   9100.0
13  2022-07-18 16:47:55  5.58  5.3  5.3  2.4  7813.0  25.80   6426.0
14  2022-07-18 16:52:55  6.14  5.3  5.3  4.0  7692.0  25.80   9123.0

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19341 entries, 0 to 19340
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ttime   19341 non-null  object
 1   pm1     19341 non-null  float64
 2   pm2     19341 non-null  float64
 3   pm3     19341 non-null  float64
 4   am      19341 non-null  float64
 5   sm      19341 non-null  float64
 6   st      19341 non-null  float64
 7   lum     19341 non-null  float64
dtypes: float64(7), object(1)
memory usage: 1.2+ MB

In [5]:
df1.corr()

C:\Users\Pranjal Paira\AppData\Local\Temp\ipykernel_28288\473017434.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.corr()

          pm1       pm2       pm3        am        sm        st       lum
pm1  1.000000  0.573090  0.552320  0.069879  0.441345 -0.122531  0.047982
pm2  0.573090  1.000000  0.922340  0.121761  0.728241 -0.205373  0.069458
pm3  0.552320  0.922340  1.000000  0.127813  0.730132 -0.185220  0.080850
am   0.069879  0.121761  0.127813  1.000000  0.148441 -0.287205  0.344563
sm   0.441345  0.728241  0.730132  0.148441  1.000000 -0.173479  0.082105
st  -0.122531 -0.205373 -0.185220 -0.287205 -0.173479  1.000000 -0.215903
lum  0.047982  0.069458  0.080850  0.344563  0.082105 -0.215903  1.000000

In [6]:
df2.head(15)

,ttime,pm1,pm2,pm3,am,sm,lum,temp,humd,pres
0,2022-07-18 15:39:58,0.83,0.00,0.00,0.0,7463.0,6547.0,23.02,90.57,92849.25
1,2022-07-18 15:44:55,1.39,0.00,0.00,0.0,7576.0,10249.0,23.47,88.37,92848.31
2,2022-07-18 15:49:55,1.95,0.00,0.00,0.0,7576.0,12636.0,23.64,85.26,92844.82
3,2022-07-18 15:54:55,2.51,0.00,0.00,0.0,7463.0,8318.0,23.62,85.93,92834.94
4,2022-07-18 15:59:56,0.55,2.51,2.51,0.0,7463.0,4149.0,23.82,86.06,92815.25
5,2022-07-18 16:04:55,1.11,2.51,2.51,0.0,7463.0,3238.0,24.27,82.98,92820.05
6,2022-07-18 16:09:55,1.67,2.51,2.51,0.0,7463.0,11642.0,24.51,81.52,92806.69
7,2022-07-18 16:14:55,2.23,2.51,2.51,0.0,7353.0,7291.0,24.53,80.96,92799.30
8,2022-07-18 16:19:55,2.79,2.51,2.51,0.0,7463.0,11621.0,24.46,81.03,92812.62
9,2022-07-18 16:24:56,3.35,2.51,2.51,0.0,7463.0,11515.0,24.28,81.64,92800.14
10,2022-07-18 16:29:55,3.91,2.51,2.51,0.0,7463.0,7860.0,24.09,82.12,92806.87
11,2022-07-18 16:34:56,4.47,2.51,2.51,0.0,7463.0,14701.0,23.88,83.13,92811.51
12,2022-07-18 16:39:56,5.02,2.51,2.51,0.0,7463.0,10522.0,24.14,82.44,92815.61
13,2022-07-18 16:44:56,5.58,2.51,2.51,0.0,7353.0,6386.0,24.06,82.05,92818.47
14,2022-07-18 16:49:56,6.14,2.51,2.51,0.0,7576.0,12066.0,23.82,83.00,92825.56

In [7]:
df2.corr()

C:\Users\Pranjal Paira\AppData\Local\Temp\ipykernel_28288\1778878097.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df2.corr()

,pm1,pm2,pm3,am,sm,lum,temp,humd,pres
pm1,1.000000,0.579420,0.559228,-0.194862,0.428794,0.043378,0.023540,0.226858,-0.342037
pm2,0.579420,1.000000,0.925259,-0.317772,0.702341,0.067508,0.039710,0.372843,-0.562632
pm3,0.559228,0.925259,1.000000,-0.323704,0.712649,0.081057,0.050155,0.376119,-0.573092
am,-0.194862,-0.317772,-0.323704,1.000000,-0.430970,0.189887,0.432209,-0.537111,0.307411
sm,0.428794,0.702341,0.712649,-0.430970,1.000000,0.089096,0.045897,0.545820,-0.637177
lum,0.043378,0.067508,0.081057,0.189887,0.089096,1.000000,0.484641,-0.264182,-0.030602
temp,0.023540,0.039710,0.050155,0.432209,0.045897,0.484641,1.000000,-0.645547,-0.071332
humd,0.226858,0.372843,0.376119,-0.537111,0.545820,-0.264182,-0.645547,1.000000,-0.369464
pres,-0.342037,-0.562632,-0.573092,0.307411,-0.637177,-0.030602,-0.071332,-0.369464,1.000000

Model 1 for df1

In [8]:
Y=df1['sm']
X=df1.drop(columns=['sm','ttime'],axis=1)

In [9]:
X.head()

    pm1  pm2  pm3   am     st      lum
0  3.63  0.0  0.0  3.2  25.65  15001.0
1  4.19  0.0  0.0  4.8  25.66  13863.0
2  4.74  0.0  0.0  4.0  25.67  13788.0
3  5.30  0.0  0.0  4.8  25.68  14383.0
4  0.55  5.3  5.3  3.2  25.69  14621.0

In [10]:
Y.head()

0    7813.0
1    7692.0
2    7813.0
3    7813.0
4    7813.0
Name: sm, dtype: float64

In [11]:

from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=16)

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [14]:
lr = LinearRegression()
dtr = DecisionTreeRegressor(max_depth=5)
rfr1 = RandomForestRegressor(n_estimators=100, random_state=16)
svr = SVR(kernel='sigmoid', gamma=1.0)

In [15]:
lr2 = LinearRegression()
dtr2 = DecisionTreeRegressor(max_depth=5)
rfr2 = RandomForestRegressor(n_estimators=100, random_state=16)
svr2 = SVR(kernel='sigmoid', gamma=1.0)

In [16]:
clfs1 = {
    'LR' : lr,
    'DTR' : dtr, 
    'RFR': rfr1,
    'SVR' : svr
}

In [17]:
clfs2 = {
    'LR' : lr,
    'DTR' : dtr, 
    'RFR': rfr2,
    'SVR' : svr
}

In [18]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [19]:
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    Y_pred = clf.predict(X_test)
    mae=  mean_absolute_error(Y_test,Y_pred)
    mse = mean_squared_error(Y_test,Y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(Y_test,Y_pred)
    
    return mae,mse,rmse,r2

In [20]:
mae = []
mse = []
rmse = []
r2 = []

for name,clf in clfs1.items():
    
    curr_mae,curr_mse,curr_rmse,curr_r2 = train_classifier(clf, X_train,Y_train,X_test,Y_test)
    
    print("For ",name)
    print("Mean Absolute Error - ", curr_mae)
    print("Mean Square Error - ", curr_mse)
    print("Root Mean Square Error - ",curr_rmse)
    print("R2 Score - ", curr_r2)
    print(end="\n")
    
    mae.append(curr_mae)
    mse.append(curr_mse)
    rmse.append(curr_rmse)
    r2.append(curr_r2)

For  LR
Mean Absolute Error -  1747.6608463082237
Mean Square Error -  3731312.8714817395
Root Mean Square Error -  1931.6606512226053
R2 Score -  0.5628680826435822

For  DTR
Mean Absolute Error -  189.8321814377462
Mean Square Error -  93095.81382875748
Root Mean Square Error -  305.1160661596788
R2 Score -  0.9890936104801471

For  RFR
Mean Absolute Error -  111.13917299289837
Mean Square Error -  59421.74518010517
Root Mean Square Error -  243.76575883438832
R2 Score -  0.9930386053654812

For  SVR
Mean Absolute Error -  2496.0199276298786
Mean Square Error -  12330423.328893773
Root Mean Square Error -  3511.470251745524
R2 Score -  -0.44453756016316315

In [21]:
model1 = RandomForestRegressor(n_estimators=100, random_state=16)
model1.fit(X_train, Y_train)

RandomForestRegressor(random_state=16)

In [22]:
Y_pred = model1.predict(X_test)

In [23]:
rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', rmse)

Root Mean Squared Error: 243.76575883438832

Model 2 for df2

In [24]:
y=df2['sm']
x=df2.drop(columns=['sm','ttime'],axis=1)

In [25]:
x.head()

    pm1   pm2   pm3   am      lum   temp   humd      pres
0  0.83  0.00  0.00  0.0   6547.0  23.02  90.57  92849.25
1  1.39  0.00  0.00  0.0  10249.0  23.47  88.37  92848.31
2  1.95  0.00  0.00  0.0  12636.0  23.64  85.26  92844.82
3  2.51  0.00  0.00  0.0   8318.0  23.62  85.93  92834.94
4  0.55  2.51  2.51  0.0   4149.0  23.82  86.06  92815.25

In [26]:
y.head()

0    7463.0
1    7576.0
2    7576.0
3    7463.0
4    7463.0
Name: sm, dtype: float64

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=16)

In [28]:
def train_classifier(clf,x_train,y_train,x_test,y_test):
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    mae_=  mean_absolute_error(y_test,y_pred)
    mse_ = mean_squared_error(y_test,y_pred)
    rmse_ = np.sqrt(mse_)
    r2_ = r2_score(y_test,y_pred)
    
    return mae_,mse_,rmse_,r2_

In [29]:
mae_ = []
mse_ = []
rmse_ = []
r2_ = []

for name,clf in clfs2.items():
    
    curr_mae_,curr_mse_,curr_rmse_,curr_r2_ = train_classifier(clf, x_train,y_train,x_test,y_test)
    
    print("For ",name)
    print("Mean Absolute Error - ", curr_mae_)
    print("Mean Square Error - ", curr_mse_)
    print("Root Mean Square Error - ",curr_rmse_)
    print("R2 Score - ", curr_r2_)
    print(end="\n")
    
    mae_.append(curr_mae_)
    mse_.append(curr_mse_)
    rmse_.append(curr_rmse_)
    r2_.append(curr_r2_)

For  LR
Mean Absolute Error -  1225.5103394876965
Mean Square Error -  2455348.006810209
Root Mean Square Error -  1566.9550110996195
R2 Score -  0.7400300769205492

For  DTR
Mean Absolute Error -  253.05232326338358
Mean Square Error -  285604.0657167092
Root Mean Square Error -  534.4193725125514
R2 Score -  0.9697605118339176

For  RFR
Mean Absolute Error -  138.23284581060983
Mean Square Error -  150702.49729618247
Root Mean Square Error -  388.2041953613877
R2 Score -  0.9840437622197324

For  SVR
Mean Absolute Error -  2640.341398116014
Mean Square Error -  13751897.351398116
Root Mean Square Error -  3708.3550735330236
R2 Score -  -0.4560378759848096

In [30]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import numpy as np

In [31]:
x.head()

    pm1   pm2   pm3   am      lum   temp   humd      pres
0  0.83  0.00  0.00  0.0   6547.0  23.02  90.57  92849.25
1  1.39  0.00  0.00  0.0  10249.0  23.47  88.37  92848.31
2  1.95  0.00  0.00  0.0  12636.0  23.64  85.26  92844.82
3  2.51  0.00  0.00  0.0   8318.0  23.62  85.93  92834.94
4  0.55  2.51  2.51  0.0   4149.0  23.82  86.06  92815.25

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=16)

In [33]:
model2 = RandomForestRegressor(n_estimators=100, random_state=16)
model2.fit(x_train, y_train)

RandomForestRegressor(random_state=16)

In [34]:
y_pred = model2.predict(x_test)

In [35]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', rmse)

Root Mean Squared Error: 388.2041953613877

In [36]:
sensor=int(input("Enter the sensor: "))
if sensor==2:
    time=input("Enter the date: ")
    pm1=float(input("Enter the pm1: "))
    pm2=float(input("Enter the pm2: "))
    pm3=float(input("Enter the pm3: "))
    am=float(input("Enter the am: "))
    lum=float(input("Enter the lum: "))
    temp=float(input("Enter the temp: "))
    humd=float(input("Enter the humd: "))
    pres=float(input("Enter the pres: "))
else:
    time=input("Enter the date: ")
    pm1=float(input("Enter the pm1: "))
    pm2=float(input("Enter the pm2: "))
    pm3=float(input("Enter the pm3: "))
    am=float(input("Enter the am: "))
    lum=float(input("Enter the lum: "))
    st=float(input("Enter the temp: "))

In [39]:
if sensor==1:
    ans=model1.predict([[pm1,pm2,pm3,am,st,lum]])
else:
    ans=model2.predict([[pm1,pm2,pm3,am,lum,temp,humd,pres]])

c:\Users\Pranjal Paira\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [40]:
print(ans)

[7565.91]